[swagger_codegen]
endpoint = "swagger_codegen.parsing.endpoint.EndpointDescription"
renderer = "swagger_codegen.render.package_renderer.PackageRenderer"

[services]

[services.petstore]
uri = "http://petstore.swagger.io:8080/api/v3/openapi.json"
directory = "example"
package = "petstore"
